# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a13347a430bc0265b52f437cd60dfba2add97939d2cb06264da2bbdaa14141a265d3b77ed329281e17a765d1b0a592f49624e645317ab13f8550189adbbad52

test:
  secret_key_base: 599a01853c4e09f86936a5bd2492eec219aae7d7f1a3a167a073754bc4fbbfd5b4827b45b1fef6bea09d303f1fb916d0cf5d473226e1c249e1f7dd1418f697e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
