# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d4cae2f8266ad0a2ff9e49f536bfb6058d874461b8242c829c850d2db8a30c13429b7e78ea1ab64de702ec7b9e97252d2224cd947931d8060163dee0ccefa8a

test:
  secret_key_base: 601bd83f70e6bd3b923a714f0887123ed4a2fe3698fc8d14140605df66697867abd306aad6a3f7059fac730c39cf0056eebc8ad3adb8e1cbe2d0c15022fb8c09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
