# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4753da30b1e464a060a7f9911064efdc79e0d44218e7d1ea1afd4265384e4b0921aed0a8f1270b36af336e03e73ac3f399c22487328e945c7c31f5c4b63ad004

test:
  secret_key_base: 70f770dbfe7bdaeb201222456959885f20db2949b866e7470c82d7d1408a7775452025be75652cbeb15b9d88fae4ba0e9676d826852d9e86639fef9d93dd209d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
